server:
  port: 9090

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 10s
#        ----request routing
      routes:
        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/api/v1/card/**, /card-service/v3/api-docs
        #          filters:
        #            - RewritePath=/card-service/(?<segment>.*), /api/v1/card/${segment}

        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/student/**, /student-service/v3/api-docs
#                filters:
#                  - RewritePath=/student-service/(?<segment>.*), /api/v1/student/${segment}
      default-filters:
        - name: DedupeResponseHeader
          args:
            strategy: RETAIN_FIRST
      discovery:
        locator:
          lower-case-service-id: true
#          ----auto mapping
#          enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /card-service/v3/api-docs
        name: Card Service
      - url: /student-service/v3/api-docs
        name: Student Service