server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false #not register itself to eureka
    fetch-registry: false #fetch service that register
  instance:
    lease-renewal-interval-in-seconds: 30
